baseurl = "https://blog.ikuamike.io/"
languageCode = "en-us"
theme = "terminal"
paginate = 7
enableemoji = true

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "green"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 3
  # show selector to switch language
  showLanguageSelector = false
  # set theme to full screen width
  fullWidthTheme = false
  # center theme with default width
  centerTheme = true
  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"
  description = "Capture The Flag Writeups :: Cyber Security :: Hacking"

[languages]
  [languages.en]
    languageName = "English"
    title = "ikuamike"
    subtitle = "Capture The Flag Writeups :: Cyber Security :: Hacking"
    description = "Blog about Cyber Security and Capture The Flag Writeups by Michael Ikua"
    keywords = ""
    copyright = "Â© Michael Ikua"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "> cd ~"
      logoHomeLink = "/"
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About Me"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "webinars"
        name = "Webinars"
        url = "/webinars"
      [[languages.en.menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags"
      [[languages.en.menu.main]]
        identifier = "all posts"
        name = "All Posts"
        url = "/all-posts"
